### ISSUE TITLE
1.6.0 npm package mistake

### ISSUE THREAD

**Issue by DyckGerman** [numical/script-ext-html-webpack-plugin#10]
It looks like 1.6.0 published to npm misses ./lib directory

I get the following error:

Cannot find module './lib/plugin.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
...<truncated>...

**Comment by numical** [comment]
Eek! Stupid error on my part.
Sorry.
Fixed now in v1.6.2.
